lib/board_games_web/router.ex
defmodule BoardGamesWeb.Router do
  use BoardGamesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BoardGamesWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BoardGamesWeb do
    pipe_through :browser

    get "/", PlayGameController, :new
    get "/play", PlayGameController, :new
    post "/play", PlayGameController, :create
    get "/play/:game_id", PlayGameController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", BoardGamesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BoardGamesWeb.Telemetry
    end
  end
end

lib/board_games_web/live/sternhalma_live.ex
defmodule BoardGamesWeb.SternhalmaLive do
  @moduledoc """
  Module to allow players to play Chinese Checkers from a browser.

  LiveView processes are created as users join a game.

  Events are sent to LiveView processes as players interact with the page.

  The shared game state is updated and changed as events are handled.

  As result of most interactions, the game state is broadcast to all
  other connected players in the game room.
  """

  use BoardGamesWeb, :live_view

  alias BoardGames.{
    GameSupervisor,
    LiveMonitor,
    GameServer,
    SternhalmaAdapter,
    BoardLocation,
    GameState
  }

  @impl true
  def mount(_params, session, socket) do
    game_id = Map.get(session, "game_id")
    player_name = Map.get(session, "player_name")

    message =
      if connected?(socket) do
        with {:ok, game} <- setup_live_view_process(game_id, player_name) do
          broadcast_game_state_update!(game_id, game)
          nil
        else
          {:error, code, game} ->
            broadcast_game_state_update!(game_id, game)
            message_for_code(code)
        end
      end

    {:ok,
     assign(socket,
       game: nil,
       game_id: game_id,
       message: message,
       player_name: player_name,
       start: nil
     )}
  end

  @doc """
  Callback that happens when the LV process is terminating.

  This allows the player to be removed from the game, and
  the entire game server process can also be terminated if
  there are no remaining players.
  """
  @spec unmount(term(), map()) :: :ok
  def unmount(_reason, %{player_id: player_id, game_id: game_id}) do
    {:ok, game} = GameServer.leave_game(game_id, player_id)
    broadcast_game_state_update!(game_id, game)

    if length(game.connected_players) == 0 do
      GameSupervisor.terminate_child(game_id)
    end

    :ok
  end

  @impl true
  def render(assigns) do
    BoardGamesWeb.SternhalmaView.render("sternhalma_live.html", assigns)
  end

  @impl true
  def handle_event("start-game", _params, socket) do
    with {:ok, game} <- GameServer.start_game(socket.assigns.game_id) do
      broadcast_game_state_update!(socket.assigns.game_id, game)
    end

    {:noreply, socket}
  end

  def handle_event("marble-click", %{"marble_id" => marble_id}, socket) do
    marble =
      socket.assigns.game.marbles
      |> Enum.find(&(&1.id === marble_id))

    marble_grid_position = SternhalmaAdapter.board_position({marble.x, marble.y})

    cell =
      Enum.find(socket.assigns.game.board, fn location ->
        location.grid_position == marble_grid_position
      end)

    {:noreply, assign(socket, start: cell)}
  end

  def handle_event("board-cell-click", %{"x" => x, "y" => y, "z" => z}, socket)
      when socket.assigns.start != nil do
    start = Map.get(socket.assigns, :start)

    board_location =
      Enum.find(socket.assigns.game.board, fn location ->
        location.grid_position == %{
          x: String.to_integer(x),
          y: String.to_integer(y),
          z: String.to_integer(z)
        }
      end)

    message =
      with {:ok, game} <- GameServer.move_marble(socket.assigns.game_id, start, board_location) do
        broadcast_game_state_update!(socket.assigns.game_id, game)
        nil
      else
        {:error, code, _state} ->
          message_for_code(code)
      end

    {:noreply, assign(socket, start: nil, message: message)}
  end

  def handle_event("board-cell-click", _params, socket) do
    {:noreply, socket}
  end

  @impl true
  def handle_info(%{event: "game_state_update", payload: game}, socket) do
    {:noreply,
     assign(socket,
       game: game,
       start: update_marble_selection(game.seconds_remaining, socket.assigns.start)
     )}
  end

  #
  # private functions
  #

  @spec setup_live_view_process(String.t(), String.t()) ::
          {:ok, GameState.t()} | {:error, atom(), GameState.t()}
  defp setup_live_view_process(game_id, player_name) do
    game_id
    |> monitor_live_view_process(player_name)
    |> ensure_game_process_exists()
    |> subscribe_to_updates()
    |> ensure_player_joins(player_name)
  end

  @spec monitor_live_view_process(String.t(), String.t()) :: term()
  defp monitor_live_view_process(game_id, player_name) do
    with :ok <-
           LiveMonitor.monitor(
             self(),
             __MODULE__,
             %{player_id: player_name, game_id: game_id}
           ) do
      {:ok, game_id}
    end
  end

  @spec ensure_game_process_exists({:ok, String.t()}) :: {:ok | :error, String.t()}
  defp ensure_game_process_exists({:ok, game_id}) do
    case GameSupervisor.start_child({GameServer, game_id}) do
      {:ok, _pid} -> {:ok, game_id}
      {:error, {:already_started, _pid}} -> {:ok, game_id}
      _ -> {:error, game_id}
    end
  end

  @spec subscribe_to_updates({:ok, String.t()}) :: String.t()
  defp subscribe_to_updates({:ok, game_id}) do
    BoardGames.PubSub.subscribe_to_game_updates(game_id)
    game_id
  end

  @spec ensure_player_joins(String.t(), String.t()) ::
          {:ok, GameState.t()} | {:error, atom(), GameState.t()}
  defp ensure_player_joins(game_id, player_name) do
    game_id
    |> GameServer.join_game(player_name)
  end

  @spec broadcast_game_state_update!(String.t(), GameState.t()) :: :ok
  defp broadcast_game_state_update!(game_id, game) do
    BoardGames.PubSub.broadcast_game_update!(game_id, game)
  end

  @spec message_for_code(atom()) :: String.t()
  defp message_for_code(:no_path), do: "Cannot move there."
  defp message_for_code(:game_in_progress), do: "Game is in progress."
  defp message_for_code(_), do: "??? wat"

  @spec update_marble_selection(non_neg_integer(), BoardLocation.t()) ::
          nil | BoardLocation.t()
  defp update_marble_selection(0, _selection_start), do: nil
  defp update_marble_selection(_seconds_remaining, selection_start), do: selection_start
end

lib/board_games_web/views/sternhalma_view.ex
defmodule BoardGamesWeb.SternhalmaView do
  @moduledoc """
  Functions that are intended to be called from templates to
  help render content, CSS, etc.
  """

  use BoardGamesWeb, :view

  alias BoardGames.{
    Marble,
    GameState,
    BoardLocation,
    SternhalmaAdapter
  }

  @board_size 465
  @min_x -0.39230484541326227
  @max_x 20.392304845413264
  @max_x 23
  @min_y 0
  @max_y 27

  @spec format_countdown(integer()) :: String.t()
  def format_countdown(seconds) do
    formatted_seconds =
      (seconds - 10)
      |> abs()
      |> Integer.to_string()
      |> String.pad_leading(2, "0")

    "00:#{formatted_seconds}"
  end

  @spec player_styles(GameState.t(), String.t()) :: String.t()
  def player_styles(game, player) do
    bg_color = background_color(game.marble_colors, player)

    [
      "--bgc:#{bg_color}",
      "--bc:#{color(game.marble_colors, player)}"
    ]
    |> Enum.join(";")
  end

  @spec player_classes(GameState.t(), String.t()) :: String.t()
  def player_classes(game, player) do
    is_turn = game.status == :playing and game.turn == player

    ["player-marble"]
    |> add_if(fn -> "highlight" end, is_turn)
    |> Enum.join(" ")
  end

  @spec marble_css_classes(GameState.t(), String.t(), String.t(), BoardLocation.t(), Marble.t()) ::
          String.t()
  def marble_css_classes(game, marble_owner, player_name, start, marble) do
    is_turn = game.status == :playing and game.turn == player_name
    last_path = game.last_move

    marble_position = SternhalmaAdapter.board_position({marble.x, marble.y})

    path_includes_marble? =
      last_path != nil and
        Enum.any?(last_path, fn location -> location.grid_position == marble_position end)

    ["marble"]
    |> add_if(fn -> "clicked" end, is_turn and marble_owner == player_name and start == nil)
    |> add_if(fn -> "glow" end, start != nil and start.grid_position == marble_position)
    |> add_if(fn -> "path" end, path_includes_marble?)
    |> Enum.join(" ")
  end

  @spec marble_styles(Marble.t(), list(String.t()), String.t(), list(BoardLocation.t())) ::
          String.t()
  def marble_styles(marble, players, player_name, last_path) do
    {left, bottom} = normalize({marble.x, marble.y})
    marble_position = SternhalmaAdapter.board_position({marble.x, marble.y})

    step_index = compute_step_index(last_path, marble_position)

    [
      "--left:#{left}px",
      "--bottom:#{bottom}px",
      "--bgc:#{marble.bg_color}",
      "--bc:#{marble.border_color}",
      "--rotation: #{rotate(players, player_name) * -1}deg",
      "color: #{text_color(marble.bg_color)}"
    ]
    |> add_if(fn -> "--path-step: \"#{step_index}\"" end, step_index != nil)
    |> Enum.join(";")
  end

  @spec board_cell_css_classes(
          GameState.t(),
          String.t(),
          BoardLocation.t(),
          BoardLocation.t(),
          list(BoardLocation.t())
        ) :: String.t()
  def board_cell_css_classes(game, player_name, start, board_location, last_path) do
    is_turn? = game.turn == player_name and game.status == :playing

    path_includes_cell? =
      last_path != nil and
        Enum.any?(last_path, fn location ->
          location.grid_position == board_location.grid_position
        end)

    ["board-cell"]
    |> add_if(fn -> "clicked" end, is_turn? and start != nil)
    |> add_if(fn -> "path" end, path_includes_cell?)
    |> Enum.join(" ")
  end

  @spec board_cell_styles(
          BoardLocation.t(),
          list(String.t()),
          String.t(),
          list(BoardLocation.t())
        ) :: String.t()
  def board_cell_styles(board_location, players, player_name, last_path) do
    {left, bottom} = normalize(board_location.screen_position)

    step_index =
      Enum.find_index(last_path, fn location ->
        location.grid_position == board_location.grid_position
      end)

    [
      "--left:#{left}px",
      "--bottom:#{bottom}px",
      "--rotation: #{rotate(players, player_name) * -1}deg",
      "color: #ffffff"
    ]
    |> add_if(fn -> "--path-step: \"#{step_index + 1}\"" end, step_index != nil)
    |> Enum.join(";")
  end

  @spec background_color(map(), String.t()) :: String.t()
  def background_color(colors, player_name) do
    color_helper(colors, player_name)
    |> Enum.at(0)
  end

  @spec color(map(), String.t()) :: String.t()
  def color(colors, player_name) do
    color_helper(colors, player_name)
    |> Enum.at(1)
  end

  @spec add_if(list(term()), term(), boolean()) :: list(term())
  defp add_if(items, _item, false) do
    items
  end

  defp add_if(items, item, true) do
    [item.() | items]
  end

  @spec compute_step_index(list(BoardLocation.t()), BoardLocation.grid_position()) ::
          nil | non_neg_integer()
  defp compute_step_index(path, _marble_position) when path == nil or length(path) == 0, do: nil

  defp compute_step_index(path, marble_position) do
    final_position = List.last(path).grid_position

    compute_step_index(final_position, marble_position, length(path))
  end

  @spec compute_step_index(
          BoardLocation.grid_position(),
          BoardLocation.grid_position(),
          non_neg_integer()
        ) :: non_neg_integer()
  defp compute_step_index(final_position, marble_position, path_length)
       when final_position == marble_position,
       do: path_length

  defp compute_step_index(_final_position, _marble_position, _path_length), do: nil

  @spec text_color(String.t()) :: String.t()
  defp text_color(<<"#", hex_color::binary>>) do
    with {:ok, <<red, green, blue>>} <- Base.decode16(hex_color, case: :mixed) do
      if red * 0.299 + green * 0.587 + blue * 0.114 > 186 do
        "#000000"
      else
        "#ffffff"
      end
    else
      _ ->
        # default to black
        "#000000"
    end
  end

  @spec rotate(list(String.t()), String.t()) :: non_neg_integer()
  def rotate(players, player_name) do
    players
    |> Enum.reverse()
    |> Enum.find_index(&(&1 == player_name))
    |> rotation()
  end

  @spec rotation(non_neg_integer()) :: non_neg_integer()
  defp rotation(0), do: 180
  defp rotation(1), do: 0
  defp rotation(2), do: 240
  defp rotation(3), do: 60
  defp rotation(4), do: 120
  defp rotation(5), do: 300
  defp rotation(_player_index), do: 0

  @spec color_helper(map(), String.t()) :: list({String.t(), String.t()})
  defp color_helper(colors, player_name) do
    colors
    |> Map.get(player_name)
    |> Tuple.to_list()
  end

  @spec normalize({number(), number()}) :: {integer(), integer()}
  defp normalize({x, y}) do
    # Fit 2d point within a box of a dimension represented by size

    # center
    x = x - (@max_x - @min_x) / 2
    y = y - (@max_y - @min_y) / 2

    # scale
    scale = max(@max_x - @min_x, @max_y - @min_y)
    x = x / scale * @board_size + 12
    y = y / scale * @board_size - 10

    x = round(x + @board_size / 2)
    y = round(y + @board_size / 2)

    {x, y}
  end
end

lib/board_games_web/templates/sternhalma/_messages.html.leex
<div class="messages">
  <%= if @game.status == :over and @game.winner != nil  do %>
    <h3>🏆 <%= @game.winner %> wins!</h3>
  <% end %>

  <%= if @message != nil do %>
    <h3 class="vanish"><%= @message %></h3>
  <% end %>
</div>

lib/board_games_web/templates/sternhalma/_players.html.leex
<div class="game-info">

  <%= if @game.status == :setup do %>

    <div>
      <%= if length(@game.players) > 1 and Enum.find(@game.players, & &1 == @player) != nil do %>
        <button phx-click="start-game" class="button">Play</button>
      <% else %>
        <button disabled title="At least two players required before starting" class="button">Play</button>
      <% end %>
    </div>

  <% end %>

  <%= if Enum.find(@game.players, & &1 == @player) == nil and @game.status == :playing do %>
    <div class="player">
      <p class="player-name"><i>This game already started -- you are only allowed to watch 👀</i></p>
    </div>
  <% end %>

  <%= if Enum.find(@game.players, & &1 == @player) == nil and @game.status == :setup do %>
    <div class="player">
      <p class="player-name"><i>This game is full -- you are only allowed to watch 👀</i></p>
    </div>
  <% end %>

  <%= for player <- @game.players do %>

    <div>
      <div class="player">
        <div class="<%= player_classes(@game, player) %>" style="<%= player_styles(@game, player) %>"></div>
        <div class="player-name">&nbsp;&nbsp;<%= player %></div>
        <%= if @game.turn == player and @game.status == :playing and @game.turn_timer_ref != nil do %>
          <div class="countdown">&nbsp;&nbsp;⏱  <%= format_countdown(@game.seconds_remaining) %></div>
        <% end %>
      </div>
    </div>

  <% end %>
</div>

lib/board_games_web/templates/sternhalma/scoreboard.html.leex
<div class="scoreboard">
  <h3>Players</h3>
  <ul>
    <%= for player <- @game.players do %>
      <li>
        <span style="color:<%= color(@game.marble_colors, player) %>;background-color: <%= background_color(@game.marble_colors, player) %>;" class="marble"></span><%= player %>
        <%= if @game.turn == player do %>
          <span class="turn-indicator">✋</span>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

lib/board_games_web/templates/sternhalma/sternhalma_live.html.leex
<%= if @game do %>

  <div class="center-flex-container">

    <%= render("_players.html", game: @game, player: Map.get(assigns, :player_name)) %>

    <%= render("_messages.html", game: @game, message: @message) %>

    <div class="board-container" style="transform:rotate(<%= rotate(@game.players, @player_name) %>deg);">

      <%= for board_location <- @game.board do %>
        <button
          <%= if @game.turn == @player_name and @start != nil do %>
            phx-click="board-cell-click"
            phx-value-x="<%= board_location.grid_position.x %>"
            phx-value-y="<%= board_location.grid_position.y %>"
            phx-value-z="<%= board_location.grid_position.z %>"
          <% end %>
            style="<%= board_cell_styles(board_location, @game.players, @player_name, @game.last_move) %>"
            class="<%= board_cell_css_classes(@game, @player_name, @start, board_location, @game.last_move) %>">
        </button>
      <% end %>

      <%= for marble <- @game.marbles do %>

        <button
          id="<%= marble.id %>"
          <%= if @game.turn == @player_name and marble.belongs_to == @player_name and @start == nil do %>
            phx-click="marble-click"
            phx-value-marble_id="<%= marble.id %>"
          <% end %>
            class="<%= marble_css_classes(@game, marble.belongs_to, @player_name, @start, marble) %>"
            style="<%= marble_styles(marble, @game.players, @player_name, @game.last_move) %>">
        </button>

      <% end %>
    </div>
  </div>


<% else %>
  <p>
  <i>No game here yet...</i>
  </p>
  <p>You can <%= link "create a new one", to: Routes.play_game_path(BoardGamesWeb.Endpoint, :new) %>.<p>
<% end %>